apiVersion: v2
name: vllm
description: |
  A Helm chart for deploying vLLM.
  vLLM is a fast and easy-to-use library for LLM inference and serving.

type: application

version: 0.3.1

appVersion: "v0.3.1"
