apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lingo.fullname" . }}
  labels:
    {{- include "lingo.labels" . | nindent 4 }}
data:
  CONCURRENCY: {{ .Values.concurrency | quote }}
  SCALE_DOWN_DELAY: {{ .Values.scaleDownDelay | quote }}
